language: generic
sudo: false

env:
  global:
    - INSTALL_EDM_VERSION=1.10.0

cache:
  directories:
    - "~/.cache"

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sh -e install-edm-linux.sh
  - export PATH="${HOME}/edm/bin:${PATH}"
  - export ETS_TOOLKIT=qt4
  - edm install -y wheel click coverage
install:
  - edm run -- python -m etstool install
script:
  - edm run -- python -m etstool test
after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
notifications:
  email:
    - travis-ci@enthought.com
